version: '3'
services:
  expresscart:
    image: "node:8"
    build: .
    container_name: "supermercado"
    environment:
      NODE_ENV: development
      NODE_PATH: /
    ports:
      - "1111:1111"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.4.10
    container_name: "supermercado-mongodb"
    volumes:
      - supermercado-mongo-data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
volumes:
  expresscart-mongo-data:
